<?php


namespace Mageplaza\GiftCard\Block\Adminhtml\Code\Edit\Tab;

use Mageplaza\GiftCard\Controller\RegistryContants;
use Mageplaza\GiftCard\Helper\Data;
use Mageplaza\GiftCard\Model\GiftCardFactory;

class Code extends \Magento\Backend\Block\Widget\Form\Generic implements \Magento\Backend\Block\Widget\Tab\TabInterface
{

    protected $_helperData;
    protected $_giftCardFactory;
    protected $_registry;

    public function __construct(\Magento\Backend\Block\Template\Context $context,
                                \Magento\Framework\Registry $registry,
                                \Magento\Framework\Data\FormFactory $formFactory,
                                array $data = [],
                                Data $helperData,
                                GiftCardFactory $giftCardFactory)
    {
        parent::__construct($context, $registry, $formFactory, $data);
        $this->_giftCardFactory = $giftCardFactory;
        $this->_helperData = $helperData;
        $this->_registry = $registry;
    }

    /**
     * @inheritDoc
     */
    public function getTabLabel()
    {
        // TODO: Implement getTabLabel() method.
        return __('Gift card information');
    }

    /**
     * @inheritDoc
     */
    public function getTabTitle()
    {
        // TODO: Implement getTabTitle() method.
       return $this->getTabLabel();
    }

    /**
     * @inheritDoc
     */
    public function canShowTab()
    {
        // TODO: Implement canShowTab() method.
        return true;
    }

    /**
     * @inheritDoc
     */
    public function isHidden()
    {
        // TODO: Implement isHidden() method.
        return false;
    }

    protected function _prepareForm()
    {
        $id = $this->getRequest()->getParam('giftcard_id');
        $form = $this->_formFactory->create();

        $model = $this->_giftCardFactory->create()->load($id);
        $code = $model->getData('code');
        $created_from = $model->getData('created_from');
        $balance = $model->getData('balance');

        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Gift Card Information')]);


        $fieldset->addField(
            'id',
            'hidden',
            [
                'name' => 'id',
                'label' => __('ID'),
                'title' => __('ID'),
                'readonly' => 'readonly',
                'value' => $id,
            ]
        );
        $fieldset->addField(
            'code',
            'text',
            [
                'name' => 'code',
                'label' => __('Code'),
                'title' => __('Code'),
                'readonly' => 'readonly',
                'value' => $code,
            ]
        );
        $fieldset->addField(
            'balance',
            'text',
            [
                'name' => 'balance',
                'label' => __('Balance'),
                'title' => __('Balance'),
                'required' => true,
                'value' => $balance,
                'class' => 'validate-number validate-greater-than-zero'
            ]
        );
        $fieldset->addField(
            'created_from',
            'text',
            [
                'name' => 'created_from',
                'label' => __('Created From'),
                'title' => __('Created From'),
                'required' => true,
                'value' => $created_from,
                'readonly' => 'readonly'
            ]
        );

        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }

    protected function _prepareLayout()
    {
        $id = $this->getRequest()->getParam('giftcard_id');

        $model = $this->_giftCardFactory->create()->load($id);
        $code = $model->getData('code');
        $this->pageConfig->getTitle()->set(strtoupper('Gift Card '.$code));

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }



}


